dependencies {
    shadowImplementation("com.github.luben:zstd-jni:1.4.9-5")
    shadowImplementation("net.java.dev.jna:jna:5.12.1")

    compileOnly("com.github.GTNewHorizons:ServerUtilities:2.4.14:dev")
    runtimeOnlyNonPublishable("com.github.GTNewHorizons:ServerUtilities:2.4.14:dev")

    compileOnly('info.journeymap:journeymap-api-forge:1.7.10-2.0.0')
    compileOnly(rfg.deobf('maven.modrinth:journeymap:5.2.20'))
    compileOnly(rfg.deobf('curse.maven:xaeros-minimap-263420:5637000'))
    compileOnly(rfg.deobf('curse.maven:xaeros-world-map-317780:5658209'))

    api("com.github.GTNewHorizons:GTNHLib:0.11.52:dev")
    implementation("com.github.GTNewHorizons:GTNHExtLib:1.0.5:dev")

    runtimeOnlyNonPublishable("com.github.GTNewHorizons:NotEnoughItems:2.8.155-GTNH:dev")

    // jvmDowngrader
    compileOnly("javax.xml.bind:jaxb-api:2.3.1")
    compileOnly("org.jetbrains:annotations:26.0.1")
    compileOnly("org.projectlombok:lombok:1.18.42") { transitive = false }
    annotationProcessor("org.projectlombok:lombok:1.18.42")

    implementation("com.google.auto.value:auto-value-annotations:1.10.4")
    annotationProcessor("com.google.auto.value:auto-value:1.10.4")
}

configurations.configureEach {
    exclude group: "com.github.GTNewHorizons", module: "CodeChickenLib"
    exclude group: "com.github.GTNewHorizons", module: "Hodgepodge"
    exclude group: "com.github.GTNewHorizons", module: "Baubles"
}
